### PR TITLE
Fix/yocto/compilation

### PR DESCRIPTION
**Pull request by mandraga**
Fixes the Yocto compilation, to be able to add v4l2rtspserver to embedded images. It also adds a section for auto generating the install files, very useful in bitbake.
I will push the recipe to open embedded once the pull request is updated.

Because the Makefile is auto generated, I deleted it and added it to the .gitignore files.

### CODE REVIEW

**Comment by mpromonet** [comment]
Hi Patrick,

Thanks for the PR.
Following exchange on the issue https://github.com/mpromonet/libv4l2cpp/issues/28, I made modification in CMakeFiles that are in conflict with yours.   
Removing Makefile is not a problem, it was before moving to cmake.   
Changing the dynamic name is more annoying, I have several projects using this one as a submodule, and then hardcoding the project name will breaks build. v4l2wrapper is not a good name as the project is now named libv4l2cpp.

Best Regards,
Michel.

**Comment by mandraga** [comment]
hi Michel
Ok, I will rebase.
What about renaming the submodule directory libv4l2cpp in v4l2rtspserver?
It could also use a simpler "project(libv4l2cpp)" to set PROJECT_NAME?
This last one would spare me a local patch of CMakelists.txt.

**Comment by mpromonet** [comment]
Hi,

Yes sure, for projectname libv4l2cpp seems better then v4l2wrapper (that is the old name of the git project).

Best Regards,
Michel.

**Comment by mandraga** [comment]
The recipe works now :). Thanks Michel.

**Pull request closed without merging**
