### PR TITLE
don't use memset() for initialization in C++

### PR DESCRIPTION
**Pull request by AndreiCherniaev**
more details https://stackoverflow.com/questions/1998752/memset-or-value-initialization-to-zero-out-a-struct

### CODE REVIEW

**Comment by mpromonet** [comment]
Hi,

The buffer structure is a POD, there is no virtual.

Best Regards,
Michel.

**Comment by AndreiCherniaev** [comment]
> Hi,
> 
> The buffer structure is a POD, there is no virtual.
> 
> Best Regards, Michel.

1) POD means Plain old data? Yes, I agree. But why you use memset ()? You can. But it is bad C++ style. Isn't it? ={} is universal must have for data initiation in C++.
2) What about caps?

**Comment by AndreiCherniaev** [comment]
@mpromonet please approve commit!

**Comment by mpromonet** [comment]
Hi @AndreiCherniaev 
Thanks, but your modifications doesnot bring improvement.
Best Regards 
Michel

**Comment by AndreiCherniaev** [comment]
my commit brings C++ style to avoid potential bugs with memory. Don't use memset() if you can make another way... memset() in [top](https://pvs-studio.com/en/blog/posts/cpp/0360/) of the most dangerous functions...

**Pull request closed without merging**
