### PR TITLE
Use epoll instead of select to solve the bug of high CPU usage.

### PR DESCRIPTION
**Pull request by mrunix**

### CODE REVIEW

**Comment by mpromonet** [comment]
Hi Michael,

Thanks for the contribution.

It's true select is quite old, but replacing 4 lines of code with a long function. For instance retrying when interupted seems useless in many case.

May you clarify the high CPU usage it solves ?

Best Regards,
Michel.

**Comment by mrunix** [comment]
If use select, the CPU usage is very high, 100%, about 50% is consumed in the kernel. When it is changed to epoll, the CPU usage problem is solved. Possible reasons are as follows:

> On Linux, select() modifies timeout to reflect the amount of time not slept; most other implementations do not do this. (POSIX.1-2001 permits either behavior.) This causes problems both when Linux code which reads timeout is ported to other operating systems, and when code is ported to Linux that reuses a struct timeval for multiple select()s in a loop without reinitializing it. Consider timeout to be undefined after select() returns.

When calling isReadable&isWritable each time in a loop, need to initialize timeval.

My workaround was to replace select with epoll.

**Comment by mpromonet** [comment]
Hi Michael,

I add a test [main.cpp](https://github.com/mpromonet/libv4l2cpp/blob/master/main.cpp), with this I did not reproduce high CPU usage. Maybe you are highly use signal, and makes select (or epoll) exit with EINTR ?

Best Regards,
Michel

**Comment by mrunix** [comment]
Yes. When call isReadable in a loop, reinitializeing tv every time, that would be OK. 

> when code is ported to Linux that reuses a struct timeval for multiple select()s in a loop without reinitializing it. Consider timeout to be undefined after select() returns.

**Pull request closed without merging**
